### PR TITLE
feat: `terragrunt` example with documentation

### LINKED ISSUE #136: docs: document how-to use `terragrunt` with `terraform-provider-minikube`
`terragrunt` is an open source tool created by [GruntWorks.io](https://gruntwork.io/), and it's used as a wrapper to `terraform` where it provides features that `terraform` cannot provide. The goal of the documentation is to show another way to use the `minikube`, `kubernetes`, and `helm` providers together because it doesn't replace `terraform` usage; it extends `terraform` usage.

This is something that I would like to document for the open source community as I'm not really sure if anyone knows this is possible because I figured it out on my own using `terraform-provider-minikube`.

There are a lot of advantages:
* `terragrunt` has dedicated support for `opentofu`, which fits with @scott-the-programmer and [GruntWorks.io](https://gruntwork.io/)'s goals to bridge the [industry licensing issue](https://www.hashicorp.com/license-faq) that's causing the migration (see #120)
* The `terraform` project is downloaded using `git`, which encourages caching and reproducible `init` / `plan` / `apply` sequences through GitOps
* You can use a common configuration for all `terraform-provider-minikube` usage, which keeps your `HCL` 100% dry while providing 100% control over common settings between different drivers (`docker`, `kvm2`, `qemu2`, ...). This has a lot to do with how the project's structure is designed, which I would like to cover.
* You can template the values within `providers` block, meaning that `kubernetes_version` from `terraform-provider-minikube` can be templated:
```terraform
locals {
  kubernetes_version = "v1.28.3"
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF
provider "minikube" {
  kubernetes_version = "${local.kubernetes_version}"
}
EOF
}
```
* You can template the values with the `remote_state` block in a similar way:
```terraform
remote_state {
  backend = "local"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    path = "${get_parent_terragrunt_dir()}/${path_relative_to_include()}/terraform.tfstate"
  }
}
```

### PR DESCRIPTION
**Pull request by caerulescens**
This pull request contains an example showing usage between  `terraform-provider-minikube` and `terragrunt`.

I tested `init`, `plan`, `apply`, `destroy` for:
* `terraform_project`
* `terragrunt_project/dev/cluster-a`
* `terragrunt_project/dev/cluster-b`

It all worked as expected; the commands take longer than they should because `terragrunt` caches the entire repository so that relative file paths work correctly, which is unavoidable iirc. 

---

close #136

### CODE REVIEW

**Comment by caerulescens** [comment]
Before merging to `main`, the `base_source_url ` and `ref` locals need to be changed so that they reference `scott-the-programmer/terraform-provider-minikube` and not `caerulescens/terraform-provider-minikube`. If I changed before merging, then it would break the example on this PR. 

Current:
```hcl
locals {
  base_source_url    = "git::git@github.com:caerulescens/terraform-provider-minikube.git//examples/guides/terragrunt/terraform_project"
  ref                = "feature/terragrunt-usage"
}
```

New:
```hcl
locals {
  base_source_url    = "git::git@github.com:scott-the-programmer/terraform-provider-minikube.git//examples/guides/terragrunt/terraform_project"
  ref                = "main"
}
```

**Comment by caerulescens** [comment]
I need to make sure the link works without SSH

**Comment by caerulescens** [comment]
@scott-the-programmer I checked and made sure the `https` link works; I changed the `git` details so that when the PR merges, then `terragrunt_project` will point to the main branch's version of `terraform_project`. I wrote the essentials in the docs, and I tried to avoid any information that might become outdated. 

I think everything is good on my end; it's ready for your review now.

**Comment by caerulescens** [comment]
The last thing I need to remember to do is check the `init`, `plan`, `apply` for `terragrunt_project/dev/cluster-a` and `terragrunt_project/dev/cluster-b` to check the url change for the `terraform` block.

**Review by scott-the-programmer — COMMENTED** [review]
Looks really good! I'll have a run through of the guide tomorrow and see if i can get it running smoothly on a few different OSes 👍🏽

**Comment by scott-the-programmer** [comment]
Great work! I was able to run through and create the clusters smoothly 👍🏽 Going to merge this through and point to this guide in the main readme

**Comment by scott-the-programmer** [comment]
Closes https://github.com/scott-the-programmer/terraform-provider-minikube/issues/136

**Comment by caerulescens** [comment]
Awesome!

**Pull request merged**
