### PR TITLE
fix: typo in `kvm_qemu_uri` default value

### LINKED ISSUE #31: `terraform apply` fails  to start `minikube_cluster`  when driver="kvm2"
Hey Scott! 

Thanks for providing and maintaining this awesome package; I think I found a typo in the source code that's causing an issue with starting the minikube cluster resource when using the KVM driver. See [here](https://github.com/scott-the-programmer/terraform-provider-minikube/blob/b28a267963ee3132de4808d3dfe4480224682c2f/minikube/schema_cluster.go#L354).

**os**: Debian 11 (bullseye)
**minikube**: 1.26.1
**libvirtd**: 7.0.0

```hcl
resource "minikube_cluster" "default" {
  cluster_name = "test"
  driver = "kvm2"
}
```

```
module.minikube-cluster.minikube_cluster.default: Creating...
╷
│ Error: Failed to start host: driver start: ensuring active networks: getting libvirt connection: connecting to libvirt socket: virError(Code=5, Domain=0, Message='no connection driver available for URI 'qemu' does not include a driver name')
│ 
│   with module.minikube-cluster.minikube_cluster.default,
│   on ../../modules/minikube-cluster/cluster.tf line 3, in resource "minikube_cluster" "default":
│    3: resource "minikube_cluster" "default" {
│ 
╵
```

It's complaining that there's no connection driver for the URI `qemu`; it seems that the URI is formatted incorrectly.

---

I regularly use minikube with the kvm driver, I have no issue starting minikube when done from the command line:

```bash
$ minikube start --driver=kvm2
😄  minikube v1.26.1 on Debian 11.5
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

```

The URI used in the logs after the successful start, 
```
I1117 13:30:24.834677  248739 driver.go:365] Setting default libvirt URI to qemu:///system
```

---

In the source code, the `kvm_qemu_uri` value is set to `qemu` by default, while the description is `///system'  The KVM QEMU connection URI. (kvm2 driver only)`. I think you intended to set the default value of `kvm_qemu_uri` to `qemu:///system`, which would make sense while the description has the extra ``///system'  ` at the beginning of the sentence.

### PR DESCRIPTION
**Pull request by caerulescens**
* fixes default values for `kvm_qemu_uri`
* removes typo from description in documentation

For more information, see #31.

---

closes #31

### CODE REVIEW

**Comment by caerulescens** [comment]
I went ahead and configured the provider to be used locally like [this](https://stackoverflow.com/questions/68182628/terraform-use-local-provider-plugin) answer describes.

---

`terraform init`:

```
$ terraform init
Initializing modules...
- minikube-cluster in ../../modules/minikube-cluster

Initializing the backend...

Initializing provider plugins...
- Finding terraform.local/local/minikube versions matching "1.0.0"...
- Finding hashicorp/kubernetes versions matching "2.13.1"...
- Finding hashicorp/helm versions matching "2.6.0"...
- Finding hashicorp/null versions matching "3.1.1"...
- Finding hashicorp/local versions matching "2.2.3"...
- Installing terraform.local/local/minikube v1.0.0...
- Installed terraform.local/local/minikube v1.0.0 (unauthenticated)
- Installing hashicorp/kubernetes v2.13.1...
- Installed hashicorp/kubernetes v2.13.1 (signed by HashiCorp)
- Installing hashicorp/helm v2.6.0...
- Installed hashicorp/helm v2.6.0 (signed by HashiCorp)
- Installing hashicorp/null v3.1.1...
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
- Installing hashicorp/local v2.2.3...
- Installed hashicorp/local v2.2.3 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Incomplete lock file information for providers
│ 
│ Due to your customized provider installation methods, Terraform was forced to calculate lock file checksums locally for the following providers:
│   - terraform.local/local/minikube
│ 
│ The current .terraform.lock.hcl file only includes checksums for linux_amd64, so Terraform running on another platform will fail to install these providers.
│ 
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)
╵
```

---

`terraform plan`:
```
$ terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.minikube-cluster.minikube_cluster.default will be created
  + resource "minikube_cluster" "default" {
      + addons                     = (known after apply)
      + apiserver_ips              = (known after apply)
      + apiserver_name             = "minikubeCA"
      + apiserver_names            = (known after apply)
      + apiserver_port             = 8443
      + base_image                 = "gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8"



       client_key                 = (sensitive value)
      + cluster_ca_certificate     = (sensitive value)
      + cluster_name               = "opencomply-local-development"
      + container_runtime          = "docker"ve value)
      + cpus                       = 2
      + delete_on_failure          = false
      + disable_driver_mounts      = false
      + disk_size                  = 20000
      + dns_domain                 = "cluster.local"
      + dns_proxy                  = false
      + driver                     = "kvm2"
      + embed_certs                = false
      + extra_disks                = 0
      + force                      = false
      + host                       = (known after apply)
      + host_dns_resolver          = true
      + host_only_cidr             = "192.168.59.1/24"
      + host_only_nic_type         = "virtio"
      + hyperkit_vsock_ports       = (known after apply)
      + hyperv_use_external_switch = false
      + id                         = (known after apply)
      + insecure_registry          = (known after apply)
      + iso_url                    = (known after apply)
      + keep_context               = false
      + kvm_gpu                    = false
      + kvm_hidden                 = false
      + kvm_network                = "default"
      + kvm_numa_count             = 1
      + kvm_qemu_uri               = "qemu:///system"
      + memory                     = 6000
      + mount                      = false
      + mount_string               = "/Users"
      + namespace                  = "default"
      + nat_nic_type               = "virtio"
      + nfs_share                  = (known after apply)
      + nfs_shares_root            = "/nfsshares"
      + no_vtx_check               = false
      + nodes                      = 1
      + ports                      = (known after apply)
      + registry_mirror            = (known after apply)
      + service_cluster_ip_range   = "10.96.0.0/12"
      + ssh_port                   = 22
      + ssh_user                   = "root"
      + vm                         = false
      + wait_timeout               = 600
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

---

`terraform apply`:
```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.minikube-cluster.minikube_cluster.default will be created
  + resource "minikube_cluster" "default" {
      + addons                     = (known after apply)
      + apiserver_ips              = (known after apply)
      + apiserver_name             = "minikubeCA"
      + apiserver_names            = (known after apply)
      + apiserver_port             = 8443
      + base_image                 = "gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8"
      + cache_images               = true
      + cert_expiration            = 26280
      + client_certificate         = (sensitive value)
      + client_key                 = (sensitive value)
      + cluster_ca_certificate     = (sensitive value)
      + cluster_name               = "opencomply-local-development"
      + container_runtime          = "docker"
      + cpus                       = 2
      + delete_on_failure          = false
      + disable_driver_mounts      = false
      + disk_size                  = 20000
      + dns_domain                 = "cluster.local"
      + dns_proxy                  = false
      + driver                     = "kvm2"
      + embed_certs                = false
      + extra_disks                = 0
      + force                      = false
      + host                       = (known after apply)
      + host_dns_resolver          = true
      + host_only_cidr             = "192.168.59.1/24"
      + host_only_nic_type         = "virtio"
      + hyperkit_vsock_ports       = (known after apply)
      + hyperv_use_external_switch = false
      + id                         = (known after apply)
      + insecure_registry          = (known after apply)
      + iso_url                    = (known after apply)
      + keep_context               = false
      + kvm_gpu                    = false
      + kvm_hidden                 = false
      + kvm_network                = "default"
      + kvm_numa_count             = 1
      + kvm_qemu_uri               = "qemu:///system"
      + memory                     = 6000
      + mount                      = false
      + mount_string               = "/Users"
      + namespace                  = "default"
      + nat_nic_type               = "virtio"
      + nfs_share                  = (known after apply)
      + nfs_shares_root            = "/nfsshares"
      + no_vtx_check               = false
      + nodes                      = 1
      + ports                      = (known after apply)
      + registry_mirror            = (known after apply)
      + service_cluster_ip_range   = "10.96.0.0/12"
      + ssh_port                   = 22
      + ssh_user                   = "root"
      + vm                         = false
      + wait_timeout               = 600
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.minikube-cluster.minikube_cluster.default: Creating...
╷
│ Error: Failed to start host: driver start: ensuring active networks: getting libvirt connection: connecting to libvirt socket: virError(Code=5, Domain=0, Message='no connection driver available for URI 'qemu' does not include a driver name')
│ 
│   with module.minikube-cluster.minikube_cluster.default,
│   on ../../modules/minikube-cluster/cluster.tf line 3, in resource "minikube_cluster" "default":
│    3: resource "minikube_cluster" "default" {
│ 
╵

```

**Comment by caerulescens** [comment]
@scott-the-programmer 

I've been doing some investigation, and it seems like the provider was still trying to connect with `'qemu'` as the connection string even after configuring the compiled provider locally. For example, the same error can be generated using:

```
$ virsh -c qemu list
error: failed to connect to the hypervisor
error: no connection driver available for URI 'qemu' does not include a driver name
```

---

The correct connection string is `qemu:///system`: 

```
$ virsh -c qemu:///system list
 Id   Name   State
--------------------


```

---

I'm not extremely experienced with golang or terraform, but I thought the below process would work fixing the configuration issue:
* I changed the default value in the source code
* ran `make build` -> successful compilation 
* copied the binary like mentioned [here](https://stackoverflow.com/questions/68182628/terraform-use-local-provider-plugin)
* cleaned the state of my terraform project and minikube (including .terraform, ~/.minikube, ..., etc.)
* downloaded the kvm2 driver using `minikube start --driver=kvm2`
* ran `minikube delete`
* ran `terraform init`, `terraform plan`, and `terraform apply`

---

@scott-the-programmer 

At this point I'm confused what I'm overlooking because I think this should be a quick fix as I've reproduced the issues; I think the way I'm testing the fix is wrong. Do you have any advice?

**Comment by caerulescens** [comment]
@scott-the-programmer I've gotten the stable version, `0.0.4`, to work correctly when starting the `minikube` with the `kvm2` driver, and I've essentially now shown the premise of #31 to be true, and #32 should fix it; see below.

Using,
```hcl
resource "minikube_cluster" "default" {
  driver = "kvm2"
  kvm_qemu_uri = "qemu:///system"
}
```

0. (Optional) May need to delete `~/.minikube` if it was incompletely initialized.
1. Download minikube kvm2 driver: `minikube start --driver=kvm2`
2. Delete minikube profile: `minikube delete`
3. Bootstrap the terraform project: `terraform init`, `terraform plan`, `terraform apply`

**Comment by scott-the-programmer** [comment]
Awesome work @caerulescens! - i'll merge in your PR and publish a new version now :) 

Thanks again!

**Pull request merged**
